-- MySQL Script generated by MySQL Workbench
-- Sat Jun 21 12:28:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plaza_Andina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plaza_Andina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plaza_Andina` DEFAULT CHARACTER SET utf8 ;
USE `plaza_Andina` ;

-- -----------------------------------------------------
-- Table `plaza_Andina`.`PLAZA_ANDINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plaza_Andina`.`PLAZA_ANDINA` (
  `cod` INT NOT NULL,
  `ubicación` VARCHAR(45) NOT NULL,
  `noMesas` INT NOT NULL,
  `noMeseros` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plaza_Andina`.`MESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plaza_Andina`.`MESA` (
  `id` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `PLAZA_ANDINA_cod` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MESA_PLAZA_ANDINA1_idx` (`PLAZA_ANDINA_cod` ASC) VISIBLE,
  CONSTRAINT `fk_MESA_PLAZA_ANDINA1`
    FOREIGN KEY (`PLAZA_ANDINA_cod`)
    REFERENCES `plaza_Andina`.`PLAZA_ANDINA` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plaza_Andina`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plaza_Andina`.`EMPLEADO` (
  `identificación` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `PLAZA_ANDINA_cod` INT NOT NULL,
  PRIMARY KEY (`identificación`),
  INDEX `fk_EMPLEADO_PLAZA_ANDINA_idx` (`PLAZA_ANDINA_cod` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_PLAZA_ANDINA`
    FOREIGN KEY (`PLAZA_ANDINA_cod`)
    REFERENCES `plaza_Andina`.`PLAZA_ANDINA` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
